### ISSUE TITLE
Please publish 0.11 on cpan because I need `set_waitpid_blocking_sleep`

### ISSUE THREAD

**Issue by KJ7LNW** [pmorch/perl-Parallel-Loops#2]
Hi there,

I spent some time today figuring out why `Parallel::Loops` was slow and figured out that `Parallel::ForkManager` has an option for `set_waitpid_blocking_sleep` which "fixes" it.  Then I found that you've already addressed this in 1525661a0f56a2c40e3184bf1e5deb3728acdd2d but version 0.11 hasn't yet been released to CPAN.

I would like to parallelize my [PDL::Opt::Simplex::Simple](https://metacpan.org/pod/PDL::Opt::Simplex::Simple) module using `Parallel::Loops`, which would require your 0.11 release to pass cpantesters.

Can you push it up to PAUSE, so it updates on CPAN?  

Thanks!

-Eric

**Comment by pmorch** [comment]
I just did. But it became 0.12 because there was a spelling bugfix too.

**Comment by KJ7LNW** [comment]
Thanks so much!
