### ISSUE TITLE
Printing to pipe error

### ISSUE THREAD

**Issue by rocketrogerdcook** [pmorch/perl-Parallel-Loops#3]
Hello. 

I'm trying to retrieve a bunch of things from the web and print progress notes about each one of them as they happen. I'm running only five processes at once. It gets about 34 iterations in and then dies with this error: 

```
Couldn't print to pipe at /home/directory/perl5/lib/perl5/Parallel/Loops.pm line 529.
Warning: unable to close filehandle GEN52 properly: Broken pipe at /home/directory/perl5/lib/perl5/Parallel/Loops.pm line 531.
```

I also see this for filehandle GEN54. Do you know what I might be doing that's triggering this? I tried wrapping all my print statements in `Fcntl qw(:flock)` (`flock(STDOUT, LOCK_EX);` and 'flock(STDOUT, LOCK_UN);`), but that didn't do it either. I tried replicating it with a simple print statement, but that didn't do it either.

Thanks for any help you can provide!

roger

**Comment by pmorch** [comment]
Hi,

Thanks for your email. Sorry, no I don't really have any idea. Could it be
that the child process died somehow?

I don't personally use Perl any longer.

Peter

**Comment by rocketrogerdcook** [comment]
Ok. I did call "die" for the faux exceptions. Do you remember if that was the right thing to do?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Peter Valdemar Mørch ***@***.***>
Sent: Wednesday, August 28, 2024 10:47:46 PM
To: pmorch/perl-Parallel-Loops ***@***.***>
Cc: Cook, Roger ***@***.***>; Author ***@***.***>
Subject: [External] Re: [pmorch/perl-Parallel-Loops] Printing to pipe error (Issue #3)


Hi,

Thanks for your email. Sorry, no I don't really have any idea. Could it be
that the child process died somehow?

I don't personally use Perl any longer.

Peter

**Comment by pmorch** [comment]
I'm sorry, no, I don't remember.

**Comment by rocketrogerdcook** [comment]
Ok. I'll close it when I get back to work.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Peter Valdemar Mørch ***@***.***>
Sent: Thursday, August 29, 2024 12:27:26 AM
To: pmorch/perl-Parallel-Loops ***@***.***>
Cc: Cook, Roger ***@***.***>; Author ***@***.***>
Subject: [External] Re: [pmorch/perl-Parallel-Loops] Printing to pipe error (Issue #3)


I'm sorry, no, I don't remember.

**Comment by rocketrogerdcook** [comment]
Turns out wrapping any `die` statements within an `eval` is essential. My mistake.
